<!-- SDK-style conversion -->
<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <RootNamespace>GlmSharp</RootNamespace>
    <AssemblyName>GlmSharp</AssemblyName>
    <OutputType>Library</OutputType>
    <Nullable>disable</Nullable>
    <PublishAot>true</PublishAot>
  </PropertyGroup>

  <PropertyGroup>
    <NoWarn>$(NoWarn);CS8981</NoWarn>
  </PropertyGroup>
</Project>