<Project Sdk="Microsoft.NET.Sdk">
<!--Verify binding redirects-->
  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <OutputType>Exe</OutputType>
    <RootNamespace>GlmSharpGenerator</RootNamespace>
    <AssemblyName>GlmSharpGenerator</AssemblyName>
    <!-- <AutoGenerateBindingRedirects>true</AutoGenerateBindingRedirects> -->
    <PlatformTarget>AnyCPU</PlatformTarget>
    <Nullable>disable</Nullable>
  </PropertyGroup>
</Project>