<!-- SDK-style conversion -->
<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <RootNamespace>GlmSharp</RootNamespace>
    <AssemblyName>GlmSharpRenewed</AssemblyName>
    <OutputType>Library</OutputType>
    <Nullable>disable</Nullable>
    <PackageId>GlmSharpRenewed</PackageId>
    <Version>1.0.0</Version>
    <RepositoryType>git</RepositoryType>
    <PublishRepositoryUrl>true</PublishRepositoryUrl>
    <RepositoryUrl>https://github.com/psuong/GlmSharp</RepositoryUrl>
    <IncludeSymbols>true</IncludeSymbols>
    <SymbolPackageFormat>snupkg</SymbolPackageFormat>
    <PackageLicenseExpression>MIT</PackageLicenseExpression>
    <IsPackable>true</IsPackable>
  </PropertyGroup>
  <PropertyGroup>
    <NoWarn>$(NoWarn);CS8981;CS8765;CS8767</NoWarn>
  </PropertyGroup>
</Project>